language: node_js
node_js:
  - "lts/*"
script:
  - yarn global add coveralls
  - yarn run full-build-test-ci
cache:
  directories:
    - "node_modules"
before_deploy:
  - yarn global add ipfs-deploy
  - yarn run build && yarn run export
deploy:
  - provider: script
    script: ipfs-deploy out
    skip_cleanup: true
    on:
      master: true